[#7, #8]  Post 및 Comment 엔티티 구현
prgrms-be-devcourse/BE-03-Prolog pull request #22
Opened 2023-01-13 09:31 UTC by hikarigin99

## 🌱 작업 사항 
### Post, Comment 구현
- 검증 로직 추가
- 추후 validation 및 연관 관계 추가 예정 

## 🦄 관련 이슈
close #7
close #8

2023-01-13 09:43 UTC, JoosungKwon commented on src/main/java/com/prgrms/prolog/domain/post/model/Post.java
> +	private void checkOverLength(String title) {
메서드를 재 사용하기 위해 포괄적인 매개변수 명과 매개변수로 길이를 받는 건 어떠신가요..?

2023-01-13 09:43 UTC, JoosungKwon commented on src/main/java/com/prgrms/prolog/domain/post/model/Post.java
> +	@Column(name = "post_id")
그냥 id로 하는게 좋을 것 같습니다!

2023-01-14 04:58 UTC, JoosungKwon requested changes

2023-01-14 04:58 UTC, JoosungKwon commented on src/main/java/com/prgrms/prolog/domain/comment/model/Comment.java
> +	@JoinColumn(name = "id")
앗 은비님 @JoinColum에서 name 파라미터는 이전에 "post_id"가 맞습니다~ 저희 FK는 그대로 도메인_id를 사용하기로 했고 도메인 내부 id인 경우에만 그냥 "id" 명으로 사용하기로 했어요!
https://boomrabbit.tistory.com/217

2023-01-14 11:34 UTC, hyena0608 commented on src/main/java/com/prgrms/prolog/domain/post/model/Post.java
> +	private final int TITLE_MAX_SIZE = 50;
혹시 final로만 선언한 이유가 있을까요 ? 🙂

2023-01-14 11:34 UTC, hyena0608 commented on src/main/java/com/prgrms/prolog/domain/post/model/Post.java
> +
파일 저장시 자동 정렬 설정 확인해보셔도 좋을거 같습니다 !

2023-01-15 07:54 UTC, Sinyoung3016 approved these changes

2023-01-16 06:32 UTC, hikarigin99 commented on src/main/java/com/prgrms/prolog/domain/post/model/Post.java
> +	private final int TITLE_MAX_SIZE = 50;
앗 깜빡했네요` static final `로 수정하였습니다🥲

2023-01-16 06:32 UTC, hikarigin99 commented on src/main/java/com/prgrms/prolog/domain/comment/model/Comment.java
> +	@JoinColumn(name = "id")
아하 넵 감사합니다!!

2023-01-16 06:35 UTC, JoosungKwon approved these changes

2023-01-16 06:38 UTC, merged